//
// 
// This code was generated by a tool. Please do not change this document in any of its parts.
// 
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Sadad PSP")]
[assembly: AssemblyCopyright("Copyright © Sadad PSP 2014-2020")]
[assembly: AssemblyTrademark("Sadad PSP")]
[assembly: NeutralResourcesLanguage("en")]

[assembly: AssemblyVersion("5.3.531.1632")]
[assembly: AssemblyFileVersion("5.3.531.1632")] 