//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PcPosSampleDll.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PcPosSampleDll.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حسابها.
        /// </summary>
        internal static string AccountList {
            get {
                return ResourceManager.GetString("AccountList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت قبض.
        /// </summary>
        internal static string Bill_Payment {
            get {
                return ResourceManager.GetString("Bill_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خرید.
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو پرداخت قبض.
        /// </summary>
        internal static string Cancel_Bill_Payment {
            get {
                return ResourceManager.GetString("Cancel_Bill_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو خرید.
        /// </summary>
        internal static string Cancel_Buy {
            get {
                return ResourceManager.GetString("Cancel_Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو پرداخت.
        /// </summary>
        internal static string Cancel_Pay {
            get {
                return ResourceManager.GetString("Cancel_Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو جستجو.
        /// </summary>
        internal static string Cancel_Search {
            get {
                return ResourceManager.GetString("Cancel_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو تراکنش.
        /// </summary>
        internal static string Cancel_Transaction {
            get {
                return ResourceManager.GetString("Cancel_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Get Card Info.
        /// </summary>
        internal static string CancelGetCardInfo {
            get {
                return ResourceManager.GetString("CancelGetCardInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبد کالا.
        /// </summary>
        internal static string Commodity_Basket {
            get {
                return ResourceManager.GetString("Commodity_Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خصوصیت.
        /// </summary>
        internal static string DeviceInfo {
            get {
                return ResourceManager.GetString("DeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب پورت سریال ارتباطی   مورد نظر الزامیست..
        /// </summary>
        internal static string Error_Choose_Serial_Port {
            get {
                return ResourceManager.GetString("Error_Choose_Serial_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد دستگاه های انتخابی باید 1 باشد..
        /// </summary>
        internal static string Error_Device_Choose_Count {
            get {
                return ResourceManager.GetString("Error_Device_Choose_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یکی از دستگاه ها را انتخاب کنید.
        /// </summary>
        internal static string Error_No_Device_Choosed {
            get {
                return ResourceManager.GetString("Error_No_Device_Choosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خرید با تعرفه.
        /// </summary>
        internal static string FixDutyBuy {
            get {
                return ResourceManager.GetString("FixDutyBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امنیت غذایی.
        /// </summary>
        internal static string Food_Safety {
            get {
                return ResourceManager.GetString("Food_Safety", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Card Info.
        /// </summary>
        internal static string GetCardInfo {
            get {
                return ResourceManager.GetString("GetCardInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت دولتی.
        /// </summary>
        internal static string Government_Payment {
            get {
                return ResourceManager.GetString("Government_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت شناسه دار.
        /// </summary>
        internal static string Inquired_Payment {
            get {
                return ResourceManager.GetString("Inquired_Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت.
        /// </summary>
        internal static string Pay {
            get {
                return ResourceManager.GetString("Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات کارت.
        /// </summary>
        internal static string Test_CardInfo {
            get {
                return ResourceManager.GetString("Test_CardInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - نسخه .
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
